// import style
import styles from "./../styles/routes/About.module.scss";

import Head from "next/head";

import Home from "@/pages";

const About = () => {
  return (
    <>
      <Head>
        <title>Next Room Rental</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      <section className={styles.section}>
        <img
          className={styles.heroImage}
          src="https://picsum.photos/id/15/600/600"
          alt="about image"
        />
        <div className={styles.description}>
          <h2>Our Mission</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias
            provident commodi, similique numquam amet dicta soluta libero,
            officia tempore reprehenderit praesentium ex reiciendis mollitia
            corporis voluptatibus voluptate magni ipsa cum.
          </p>
        </div>
      </section>
    </>
  );
};

export default About;
