import Head from "next/head";

import Home from "@/pages";

const Contacts = () => {
  return (
    <>
      <Head>
        <title>Next Room Rental</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      <h1>Contact Us</h1>
      <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minima,
        consequuntur! Aspernatur minus magnam impedit voluptatum possimus dicta
        aut, hic asperiores.
      </p>
    </>
  );
};

export default Contacts;
